Add to pipenv.md/helen vu
kenny-cfg/cfg-202309-software-3 pull request #2
Opened 2023-10-18 14:51 UTC by hvuvuzella

2023-10-18 19:04 UTC, kenny-cfg requested changes

2023-10-18 19:04 UTC, kenny-cfg commented on cheat_sheets/pipenv.md
> +You'll have to install the `pipenv` program first. You can do this using `pip install --user pipenv`, or `pip3 install pipenv` if you have Python3 installed. Check that it has installed by typing `pi
This isn't quite right: Python 3 is the only supported version of Python these days.

However, on older Macs (for instance), the system itself uses Python 2, which means that running Python 3 uses the `python3` command, and `pip3` for pip.

2023-10-18 19:04 UTC, kenny-cfg commented on cheat_sheets/pipenv.md
> +* `python3 -m site --user-base` to find your user base directory of Python. Change `python3` to `python` if you have that version installed instead
```suggestion
* `python3 -m site --user-base` to find your user base directory of Python. Change `python3` to `python` if you need to
```

2023-10-19 07:52 UTC, hvuvuzella commented on cheat_sheets/pipenv.md
> +* `python3 -m site --user-base` to find your user base directory of Python. Change `python3` to `python` if you have that version installed instead
I saw I made a typo “difficult” should be “difficulty”

2023-10-27 21:25 UTC, kenny-cfg approved these changes

2023-11-25 10:43 UTC, merged